-- ============================================================================
-- OKRoutcomeFlow — consolidated schema baseline
--
-- Generated by drizzle-kit introspection of the live database (project
-- cgsjmrxtuyrfvkuqjvin) on 2026-07-14. This file is DOCUMENTATION: the
-- readable answer to "what does the schema look like" without replaying
-- the 38 incremental migrations in supabase/migrations/ (which remain the
-- source of truth for schema changes).
--
-- Regenerate: npx drizzle-kit pull --config=drizzle.baseline.config.ts
-- (from apps/api), then copy the generated .sql over this file, keeping
-- this header.
-- ============================================================================
-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TYPE "public"."app_role" AS ENUM('admin', 'manager', 'contributor', 'viewer');--> statement-breakpoint
CREATE TYPE "public"."automation_action" AS ENUM('change_initiative_status', 'change_task_status', 'send_notification', 'create_update');--> statement-breakpoint
CREATE TYPE "public"."automation_trigger" AS ENUM('task_status_change', 'all_tasks_done', 'initiative_status_change', 'due_date_passed');--> statement-breakpoint
CREATE TYPE "public"."custom_field_type" AS ENUM('text', 'number', 'select', 'multi_select', 'date', 'checkbox');--> statement-breakpoint
CREATE TYPE "public"."entity_type" AS ENUM('kr', 'initiative', 'task');--> statement-breakpoint
CREATE TYPE "public"."initiative_status" AS ENUM('not_started', 'in_progress', 'completed', 'blocked');--> statement-breakpoint
CREATE TYPE "public"."invitation_status" AS ENUM('pending', 'accepted', 'revoked');--> statement-breakpoint
CREATE TYPE "public"."metric_direction" AS ENUM('increase', 'decrease', 'maintain');--> statement-breakpoint
CREATE TYPE "public"."notification_type" AS ENUM('mention', 'review_reminder', 'task_assigned', 'task_overdue');--> statement-breakpoint
CREATE TYPE "public"."review_frequency" AS ENUM('weekly', 'biweekly', 'monthly', 'quarterly');--> statement-breakpoint
CREATE TYPE "public"."review_session_status" AS ENUM('scheduled', 'completed', 'cancelled');--> statement-breakpoint
CREATE TYPE "public"."task_status" AS ENUM('todo', 'in_progress', 'blocked', 'done');--> statement-breakpoint
CREATE TYPE "public"."update_kind" AS ENUM('comment', 'progress', 'blocker', 'decision');--> statement-breakpoint
CREATE TYPE "public"."user_status" AS ENUM('pending', 'active', 'inactive');--> statement-breakpoint
CREATE TABLE "notification_preferences" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"notification_type" text NOT NULL,
	"in_app_enabled" boolean DEFAULT true NOT NULL,
	"email_enabled" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "notification_preferences_user_id_notification_type_key" UNIQUE("user_id","notification_type")
);
--> statement-breakpoint
ALTER TABLE "notification_preferences" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "kr_metric_config" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"key_result_id" uuid NOT NULL,
	"metric_name" text NOT NULL,
	"unit" text NOT NULL,
	"direction" "metric_direction" NOT NULL,
	"start_value" numeric NOT NULL,
	"target_value" numeric NOT NULL,
	"start_date" date NOT NULL,
	"end_date" date NOT NULL,
	CONSTRAINT "kr_metric_config_unique" UNIQUE("key_result_id")
);
--> statement-breakpoint
ALTER TABLE "kr_metric_config" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "kr_metric_values" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"kr_metric_config_id" uuid NOT NULL,
	"date" date NOT NULL,
	"value" numeric NOT NULL,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "kr_metric_values_unique" UNIQUE("kr_metric_config_id","date")
);
--> statement-breakpoint
ALTER TABLE "kr_metric_values" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "initiative_kr_links" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"initiative_id" uuid NOT NULL,
	"key_result_id" uuid NOT NULL,
	"weight" numeric,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "initiative_kr_links_initiative_id_key_result_id_key" UNIQUE("initiative_id","key_result_id")
);
--> statement-breakpoint
ALTER TABLE "initiative_kr_links" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "initiatives" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"owner_id" uuid,
	"status" "initiative_status" DEFAULT 'not_started' NOT NULL,
	"start_date" date,
	"end_date" date,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"color" text
);
--> statement-breakpoint
ALTER TABLE "initiatives" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "kr_review_cadence" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"key_result_id" uuid NOT NULL,
	"frequency" "review_frequency" NOT NULL,
	"day_of_week" integer,
	"time" text DEFAULT '09:00' NOT NULL,
	"next_review_date" date NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "unique_kr_cadence" UNIQUE("key_result_id"),
	CONSTRAINT "kr_review_cadence_day_of_week_check" CHECK ((day_of_week IS NULL) OR ((day_of_week >= 0) AND (day_of_week <= 6)))
);
--> statement-breakpoint
ALTER TABLE "kr_review_cadence" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "kr_review_sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"key_result_id" uuid NOT NULL,
	"review_date" date NOT NULL,
	"status" "review_session_status" DEFAULT 'scheduled' NOT NULL,
	"notes" text,
	"completed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "kr_review_sessions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "kr_review_participants" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"review_session_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	CONSTRAINT "unique_session_participant" UNIQUE("review_session_id","user_id")
);
--> statement-breakpoint
ALTER TABLE "kr_review_participants" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "organization_memberships" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"organization_id" uuid NOT NULL,
	"is_active" boolean DEFAULT false NOT NULL,
	"joined_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "organization_memberships_user_id_organization_id_key" UNIQUE("user_id","organization_id")
);
--> statement-breakpoint
ALTER TABLE "organization_memberships" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "updates" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"entity_type" "entity_type" NOT NULL,
	"entity_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"update_kind" "update_kind" NOT NULL,
	"content" text NOT NULL,
	"pinned" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "updates" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "update_mentions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"update_id" uuid NOT NULL,
	"mentioned_user_id" uuid NOT NULL,
	CONSTRAINT "update_mentions_update_id_mentioned_user_id_key" UNIQUE("update_id","mentioned_user_id")
);
--> statement-breakpoint
ALTER TABLE "update_mentions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "update_reactions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"update_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"reaction_type" text NOT NULL,
	CONSTRAINT "update_reactions_update_id_user_id_reaction_type_key" UNIQUE("update_id","user_id","reaction_type")
);
--> statement-breakpoint
ALTER TABLE "update_reactions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "notifications" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"type" "notification_type" NOT NULL,
	"entity_type" "entity_type",
	"entity_id" uuid,
	"message" text NOT NULL,
	"read" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "notifications" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "tasks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"initiative_id" uuid NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"assignee_user_id" uuid,
	"assignee_team_id" uuid,
	"status" "task_status" DEFAULT 'todo' NOT NULL,
	"start_date" date,
	"due_date" date,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"color" text,
	"parent_task_id" uuid,
	"recurrence_rule" jsonb,
	CONSTRAINT "check_dates" CHECK ((start_date IS NULL) OR (due_date IS NULL) OR (due_date >= start_date)),
	CONSTRAINT "check_single_assignee" CHECK (NOT ((assignee_user_id IS NOT NULL) AND (assignee_team_id IS NOT NULL)))
);
--> statement-breakpoint
ALTER TABLE "tasks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "file_attachments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"entity_type" "entity_type" NOT NULL,
	"entity_id" uuid NOT NULL,
	"file_name" text NOT NULL,
	"file_size" bigint DEFAULT 0 NOT NULL,
	"file_type" text,
	"storage_path" text NOT NULL,
	"uploaded_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "file_attachments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "automations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"name" text NOT NULL,
	"trigger_type" "automation_trigger" NOT NULL,
	"trigger_config" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"action_type" "automation_action" NOT NULL,
	"action_config" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "automations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "platform_admins" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "platform_admins_email_unique" UNIQUE("email"),
	CONSTRAINT "platform_admins_email_lowercase" CHECK (email = lower(email))
);
--> statement-breakpoint
ALTER TABLE "platform_admins" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "organizations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text DEFAULT 'New Organization' NOT NULL,
	"logo_url" text,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "organizations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "organization_domains" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"domain" text NOT NULL,
	"verified" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "domain_unique" UNIQUE("domain"),
	CONSTRAINT "domain_lowercase" CHECK (domain = lower(TRIM(BOTH FROM domain)))
);
--> statement-breakpoint
ALTER TABLE "organization_domains" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "users_profile" (
	"id" uuid PRIMARY KEY NOT NULL,
	"organization_id" uuid,
	"email" text NOT NULL,
	"name" text DEFAULT '' NOT NULL,
	"avatar_url" text,
	"status" "user_status" DEFAULT 'pending' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "email_unique" UNIQUE("email"),
	CONSTRAINT "email_lowercase" CHECK (email = lower(TRIM(BOTH FROM email)))
);
--> statement-breakpoint
ALTER TABLE "users_profile" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "generic_domains" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"domain" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "generic_domains_domain_key" UNIQUE("domain")
);
--> statement-breakpoint
ALTER TABLE "generic_domains" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "user_invitations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"email" text NOT NULL,
	"role" "app_role" NOT NULL,
	"token" text,
	"status" "invitation_status" DEFAULT 'pending' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"token_hash" text,
	"expires_at" timestamp with time zone DEFAULT (now() + '7 days'::interval),
	CONSTRAINT "user_invitations_token_key" UNIQUE("token")
);
--> statement-breakpoint
ALTER TABLE "user_invitations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "task_dependencies" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"task_id" uuid NOT NULL,
	"depends_on_task_id" uuid NOT NULL,
	"dependency_type" text DEFAULT 'blocks' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "task_dependencies_task_id_depends_on_task_id_key" UNIQUE("task_id","depends_on_task_id"),
	CONSTRAINT "task_dependencies_dependency_type_check" CHECK (dependency_type = ANY (ARRAY['blocks'::text, 'waiting_on'::text]))
);
--> statement-breakpoint
ALTER TABLE "task_dependencies" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "user_roles" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"role" "app_role" NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"organization_id" uuid,
	CONSTRAINT "user_roles_user_id_role_org_key" UNIQUE("user_id","role","organization_id")
);
--> statement-breakpoint
ALTER TABLE "user_roles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "initiative_share_links" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"initiative_id" uuid NOT NULL,
	"token" text DEFAULT (gen_random_uuid()) NOT NULL,
	"created_by" uuid,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "initiative_share_links_token_key" UNIQUE("token")
);
--> statement-breakpoint
ALTER TABLE "initiative_share_links" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "teams" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "teams_org_name_unique" UNIQUE("organization_id","name")
);
--> statement-breakpoint
ALTER TABLE "teams" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "team_members" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"team_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "team_members_unique" UNIQUE("team_id","user_id")
);
--> statement-breakpoint
ALTER TABLE "team_members" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "objectives" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "objectives" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "key_results" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"objective_id" uuid,
	"parent_kr_id" uuid,
	"title" text NOT NULL,
	"description" text,
	"owner_id" uuid,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "kr_hierarchy_check" CHECK (((objective_id IS NOT NULL) AND (parent_kr_id IS NULL)) OR ((objective_id IS NULL) AND (parent_kr_id IS NOT NULL)))
);
--> statement-breakpoint
ALTER TABLE "key_results" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "custom_field_definitions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"name" text NOT NULL,
	"field_type" "custom_field_type" NOT NULL,
	"options" jsonb DEFAULT '[]'::jsonb,
	"entity_type" "entity_type" DEFAULT 'task' NOT NULL,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "custom_field_definitions_organization_id_name_entity_type_key" UNIQUE("organization_id","name","entity_type")
);
--> statement-breakpoint
ALTER TABLE "custom_field_definitions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "custom_field_values" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"field_definition_id" uuid NOT NULL,
	"entity_type" "entity_type" NOT NULL,
	"entity_id" uuid NOT NULL,
	"value" jsonb DEFAULT '""'::jsonb NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "custom_field_values_field_definition_id_entity_id_key" UNIQUE("field_definition_id","entity_id")
);
--> statement-breakpoint
ALTER TABLE "custom_field_values" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "task_watchers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"task_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "task_watchers_task_id_user_id_key" UNIQUE("task_id","user_id")
);
--> statement-breakpoint
ALTER TABLE "task_watchers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "initiative_share_viewers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"share_link_id" uuid NOT NULL,
	"email" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "initiative_share_viewers_share_link_id_email_key" UNIQUE("share_link_id","email")
);
--> statement-breakpoint
ALTER TABLE "initiative_share_viewers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "notification_preferences" ADD CONSTRAINT "notification_preferences_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users_profile"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "kr_metric_config" ADD CONSTRAINT "kr_metric_config_key_result_id_fkey" FOREIGN KEY ("key_result_id") REFERENCES "public"."key_results"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "kr_metric_values" ADD CONSTRAINT "kr_metric_values_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users_profile"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "kr_metric_values" ADD CONSTRAINT "kr_metric_values_kr_metric_config_id_fkey" FOREIGN KEY ("kr_metric_config_id") REFERENCES "public"."kr_metric_config"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "initiative_kr_links" ADD CONSTRAINT "initiative_kr_links_initiative_id_fkey" FOREIGN KEY ("initiative_id") REFERENCES "public"."initiatives"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "initiative_kr_links" ADD CONSTRAINT "initiative_kr_links_key_result_id_fkey" FOREIGN KEY ("key_result_id") REFERENCES "public"."key_results"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "initiatives" ADD CONSTRAINT "initiatives_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users_profile"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "initiatives" ADD CONSTRAINT "initiatives_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "initiatives" ADD CONSTRAINT "initiatives_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "public"."users_profile"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "kr_review_cadence" ADD CONSTRAINT "kr_review_cadence_key_result_id_fkey" FOREIGN KEY ("key_result_id") REFERENCES "public"."key_results"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "kr_review_sessions" ADD CONSTRAINT "kr_review_sessions_key_result_id_fkey" FOREIGN KEY ("key_result_id") REFERENCES "public"."key_results"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "kr_review_participants" ADD CONSTRAINT "kr_review_participants_review_session_id_fkey" FOREIGN KEY ("review_session_id") REFERENCES "public"."kr_review_sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "kr_review_participants" ADD CONSTRAINT "kr_review_participants_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users_profile"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "organization_memberships" ADD CONSTRAINT "organization_memberships_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "organization_memberships" ADD CONSTRAINT "organization_memberships_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "updates" ADD CONSTRAINT "updates_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "updates" ADD CONSTRAINT "updates_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users_profile"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "update_mentions" ADD CONSTRAINT "update_mentions_mentioned_user_id_fkey" FOREIGN KEY ("mentioned_user_id") REFERENCES "public"."users_profile"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "update_mentions" ADD CONSTRAINT "update_mentions_update_id_fkey" FOREIGN KEY ("update_id") REFERENCES "public"."updates"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "update_reactions" ADD CONSTRAINT "update_reactions_update_id_fkey" FOREIGN KEY ("update_id") REFERENCES "public"."updates"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "update_reactions" ADD CONSTRAINT "update_reactions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users_profile"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users_profile"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_assignee_team_id_fkey" FOREIGN KEY ("assignee_team_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_assignee_user_id_fkey" FOREIGN KEY ("assignee_user_id") REFERENCES "public"."users_profile"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users_profile"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_initiative_id_fkey" FOREIGN KEY ("initiative_id") REFERENCES "public"."initiatives"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_parent_task_id_fkey" FOREIGN KEY ("parent_task_id") REFERENCES "public"."tasks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "file_attachments" ADD CONSTRAINT "file_attachments_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "file_attachments" ADD CONSTRAINT "file_attachments_uploaded_by_fkey" FOREIGN KEY ("uploaded_by") REFERENCES "public"."users_profile"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "automations" ADD CONSTRAINT "automations_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users_profile"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "automations" ADD CONSTRAINT "automations_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "organization_domains" ADD CONSTRAINT "organization_domains_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users_profile" ADD CONSTRAINT "users_profile_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users_profile" ADD CONSTRAINT "users_profile_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_invitations" ADD CONSTRAINT "user_invitations_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_dependencies" ADD CONSTRAINT "task_dependencies_depends_on_task_id_fkey" FOREIGN KEY ("depends_on_task_id") REFERENCES "public"."tasks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_dependencies" ADD CONSTRAINT "task_dependencies_task_id_fkey" FOREIGN KEY ("task_id") REFERENCES "public"."tasks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "initiative_share_links" ADD CONSTRAINT "initiative_share_links_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users_profile"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "initiative_share_links" ADD CONSTRAINT "initiative_share_links_initiative_id_fkey" FOREIGN KEY ("initiative_id") REFERENCES "public"."initiatives"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "teams" ADD CONSTRAINT "teams_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "team_members" ADD CONSTRAINT "team_members_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "team_members" ADD CONSTRAINT "team_members_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users_profile"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "objectives" ADD CONSTRAINT "objectives_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users_profile"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "objectives" ADD CONSTRAINT "objectives_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "key_results" ADD CONSTRAINT "key_results_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users_profile"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "key_results" ADD CONSTRAINT "key_results_objective_id_fkey" FOREIGN KEY ("objective_id") REFERENCES "public"."objectives"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "key_results" ADD CONSTRAINT "key_results_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "key_results" ADD CONSTRAINT "key_results_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "public"."users_profile"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "key_results" ADD CONSTRAINT "key_results_parent_kr_id_fkey" FOREIGN KEY ("parent_kr_id") REFERENCES "public"."key_results"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "custom_field_definitions" ADD CONSTRAINT "custom_field_definitions_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users_profile"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "custom_field_definitions" ADD CONSTRAINT "custom_field_definitions_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "custom_field_values" ADD CONSTRAINT "custom_field_values_field_definition_id_fkey" FOREIGN KEY ("field_definition_id") REFERENCES "public"."custom_field_definitions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_watchers" ADD CONSTRAINT "task_watchers_task_id_fkey" FOREIGN KEY ("task_id") REFERENCES "public"."tasks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_watchers" ADD CONSTRAINT "task_watchers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users_profile"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "initiative_share_viewers" ADD CONSTRAINT "initiative_share_viewers_share_link_id_fkey" FOREIGN KEY ("share_link_id") REFERENCES "public"."initiative_share_links"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_updates_entity" ON "updates" USING btree ("entity_type" enum_ops,"entity_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_updates_organization" ON "updates" USING btree ("organization_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_updates_user" ON "updates" USING btree ("user_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_update_mentions_update" ON "update_mentions" USING btree ("update_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_update_reactions_update" ON "update_reactions" USING btree ("update_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_notifications_created_at" ON "notifications" USING btree ("created_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "idx_notifications_read" ON "notifications" USING btree ("user_id" bool_ops,"read" bool_ops);--> statement-breakpoint
CREATE INDEX "idx_notifications_user_id" ON "notifications" USING btree ("user_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_org_domains_org_id" ON "organization_domains" USING btree ("organization_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_users_profile_org_id" ON "users_profile" USING btree ("organization_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_users_profile_status" ON "users_profile" USING btree ("status" enum_ops);--> statement-breakpoint
CREATE INDEX "idx_user_invitations_email" ON "user_invitations" USING btree ("email" text_ops);--> statement-breakpoint
CREATE INDEX "idx_user_invitations_organization_id" ON "user_invitations" USING btree ("organization_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_user_invitations_token" ON "user_invitations" USING btree ("token" text_ops);--> statement-breakpoint
CREATE INDEX "idx_user_roles_user_id" ON "user_roles" USING btree ("user_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_teams_organization_id" ON "teams" USING btree ("organization_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_team_members_team_id" ON "team_members" USING btree ("team_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_team_members_user_id" ON "team_members" USING btree ("user_id" uuid_ops);--> statement-breakpoint
CREATE VIEW "public"."user_invitations_safe" AS (SELECT id, organization_id, email, role, status, expires_at, created_at FROM user_invitations ui WHERE organization_id = get_user_org_id(auth.uid()) AND (has_role(auth.uid(), 'admin'::app_role) OR has_role(auth.uid(), 'manager'::app_role) OR is_platform_admin(auth.uid())));--> statement-breakpoint
CREATE POLICY "Users can view their own notification preferences" ON "notification_preferences" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((is_platform_admin(auth.uid()) OR (user_id = auth.uid())));--> statement-breakpoint
CREATE POLICY "Users can manage their own notification preferences" ON "notification_preferences" AS PERMISSIVE FOR ALL TO "authenticated";--> statement-breakpoint
CREATE POLICY "Users can view org kr metric configs" ON "kr_metric_config" AS PERMISSIVE FOR SELECT TO public USING ((is_platform_admin(auth.uid()) OR (EXISTS ( SELECT 1
   FROM key_results kr
  WHERE ((kr.id = kr_metric_config.key_result_id) AND (kr.organization_id = get_user_org_id(auth.uid())))))));--> statement-breakpoint
CREATE POLICY "Managers and owners can create kr metric configs" ON "kr_metric_config" AS PERMISSIVE FOR INSERT TO public;--> statement-breakpoint
CREATE POLICY "Managers and owners can update kr metric configs" ON "kr_metric_config" AS PERMISSIVE FOR UPDATE TO public;--> statement-breakpoint
CREATE POLICY "Managers and owners can delete kr metric configs" ON "kr_metric_config" AS PERMISSIVE FOR DELETE TO public;--> statement-breakpoint
CREATE POLICY "Users can view org kr metric values" ON "kr_metric_values" AS PERMISSIVE FOR SELECT TO public USING ((is_platform_admin(auth.uid()) OR (EXISTS ( SELECT 1
   FROM (kr_metric_config mc
     JOIN key_results kr ON ((kr.id = mc.key_result_id)))
  WHERE ((mc.id = kr_metric_values.kr_metric_config_id) AND (kr.organization_id = get_user_org_id(auth.uid())))))));--> statement-breakpoint
CREATE POLICY "Managers and owners can create kr metric values" ON "kr_metric_values" AS PERMISSIVE FOR INSERT TO public;--> statement-breakpoint
CREATE POLICY "Managers and owners can update kr metric values" ON "kr_metric_values" AS PERMISSIVE FOR UPDATE TO public;--> statement-breakpoint
CREATE POLICY "Managers and owners can delete kr metric values" ON "kr_metric_values" AS PERMISSIVE FOR DELETE TO public;--> statement-breakpoint
CREATE POLICY "Users can view org initiative_kr_links" ON "initiative_kr_links" AS PERMISSIVE FOR SELECT TO public USING ((is_platform_admin(auth.uid()) OR (EXISTS ( SELECT 1
   FROM initiatives i
  WHERE ((i.id = initiative_kr_links.initiative_id) AND (i.organization_id = get_user_org_id(auth.uid())))))));--> statement-breakpoint
CREATE POLICY "Managers and owners can create initiative_kr_links" ON "initiative_kr_links" AS PERMISSIVE FOR INSERT TO public;--> statement-breakpoint
CREATE POLICY "Managers and owners can update initiative_kr_links" ON "initiative_kr_links" AS PERMISSIVE FOR UPDATE TO public;--> statement-breakpoint
CREATE POLICY "Managers and owners can delete initiative_kr_links" ON "initiative_kr_links" AS PERMISSIVE FOR DELETE TO public;--> statement-breakpoint
CREATE POLICY "Users can view org initiatives" ON "initiatives" AS PERMISSIVE FOR SELECT TO public USING ((is_platform_admin(auth.uid()) OR (organization_id = get_user_org_id(auth.uid()))));--> statement-breakpoint
CREATE POLICY "Admins and managers can create initiatives" ON "initiatives" AS PERMISSIVE FOR INSERT TO public;--> statement-breakpoint
CREATE POLICY "Admins and managers can update any initiatives" ON "initiatives" AS PERMISSIVE FOR UPDATE TO public;--> statement-breakpoint
CREATE POLICY "Initiative owners can update their initiatives" ON "initiatives" AS PERMISSIVE FOR UPDATE TO public;--> statement-breakpoint
CREATE POLICY "Admins and managers can delete initiatives" ON "initiatives" AS PERMISSIVE FOR DELETE TO public;--> statement-breakpoint
CREATE POLICY "Users can view org kr_review_cadence" ON "kr_review_cadence" AS PERMISSIVE FOR SELECT TO public USING ((is_platform_admin(auth.uid()) OR (EXISTS ( SELECT 1
   FROM key_results kr
  WHERE ((kr.id = kr_review_cadence.key_result_id) AND (kr.organization_id = get_user_org_id(auth.uid())))))));--> statement-breakpoint
CREATE POLICY "Managers and KR owners can insert kr_review_cadence" ON "kr_review_cadence" AS PERMISSIVE FOR INSERT TO public;--> statement-breakpoint
CREATE POLICY "Managers and KR owners can update kr_review_cadence" ON "kr_review_cadence" AS PERMISSIVE FOR UPDATE TO public;--> statement-breakpoint
CREATE POLICY "Managers and KR owners can delete kr_review_cadence" ON "kr_review_cadence" AS PERMISSIVE FOR DELETE TO public;--> statement-breakpoint
CREATE POLICY "Users can view org kr_review_sessions" ON "kr_review_sessions" AS PERMISSIVE FOR SELECT TO public USING ((is_platform_admin(auth.uid()) OR (EXISTS ( SELECT 1
   FROM key_results kr
  WHERE ((kr.id = kr_review_sessions.key_result_id) AND (kr.organization_id = get_user_org_id(auth.uid())))))));--> statement-breakpoint
CREATE POLICY "Managers and KR owners can insert kr_review_sessions" ON "kr_review_sessions" AS PERMISSIVE FOR INSERT TO public;--> statement-breakpoint
CREATE POLICY "Managers and KR owners can update kr_review_sessions" ON "kr_review_sessions" AS PERMISSIVE FOR UPDATE TO public;--> statement-breakpoint
CREATE POLICY "Managers and KR owners can delete kr_review_sessions" ON "kr_review_sessions" AS PERMISSIVE FOR DELETE TO public;--> statement-breakpoint
CREATE POLICY "Users can view org kr_review_participants" ON "kr_review_participants" AS PERMISSIVE FOR SELECT TO public USING ((is_platform_admin(auth.uid()) OR (EXISTS ( SELECT 1
   FROM (kr_review_sessions rs
     JOIN key_results kr ON ((kr.id = rs.key_result_id)))
  WHERE ((rs.id = kr_review_participants.review_session_id) AND (kr.organization_id = get_user_org_id(auth.uid())))))));--> statement-breakpoint
CREATE POLICY "Managers and session owners can insert kr_review_participants" ON "kr_review_participants" AS PERMISSIVE FOR INSERT TO public;--> statement-breakpoint
CREATE POLICY "Managers and session owners can delete kr_review_participants" ON "kr_review_participants" AS PERMISSIVE FOR DELETE TO public;--> statement-breakpoint
CREATE POLICY "Users can view their own memberships" ON "organization_memberships" AS PERMISSIVE FOR SELECT TO "authenticated" USING (((user_id = auth.uid()) OR is_platform_admin(auth.uid())));--> statement-breakpoint
CREATE POLICY "Platform admins can manage memberships" ON "organization_memberships" AS PERMISSIVE FOR ALL TO "authenticated";--> statement-breakpoint
CREATE POLICY "Users can view org updates" ON "updates" AS PERMISSIVE FOR SELECT TO public USING ((is_platform_admin(auth.uid()) OR (organization_id = get_user_org_id(auth.uid()))));--> statement-breakpoint
CREATE POLICY "Users can create updates" ON "updates" AS PERMISSIVE FOR INSERT TO public;--> statement-breakpoint
CREATE POLICY "Authorized users can update pinned status" ON "updates" AS PERMISSIVE FOR UPDATE TO public;--> statement-breakpoint
CREATE POLICY "Authors and managers can delete updates" ON "updates" AS PERMISSIVE FOR DELETE TO public;--> statement-breakpoint
CREATE POLICY "Users can view org update mentions" ON "update_mentions" AS PERMISSIVE FOR SELECT TO public USING ((is_platform_admin(auth.uid()) OR (get_org_id_from_update(update_id) = get_user_org_id(auth.uid()))));--> statement-breakpoint
CREATE POLICY "Update authors can create mentions" ON "update_mentions" AS PERMISSIVE FOR INSERT TO public;--> statement-breakpoint
CREATE POLICY "Update authors can delete mentions" ON "update_mentions" AS PERMISSIVE FOR DELETE TO public;--> statement-breakpoint
CREATE POLICY "Users can view org update reactions" ON "update_reactions" AS PERMISSIVE FOR SELECT TO public USING ((is_platform_admin(auth.uid()) OR (get_org_id_from_update(update_id) = get_user_org_id(auth.uid()))));--> statement-breakpoint
CREATE POLICY "Org members can add reactions" ON "update_reactions" AS PERMISSIVE FOR INSERT TO public;--> statement-breakpoint
CREATE POLICY "Users can remove their own reactions" ON "update_reactions" AS PERMISSIVE FOR DELETE TO public;--> statement-breakpoint
CREATE POLICY "Users can view their own notifications" ON "notifications" AS PERMISSIVE FOR SELECT TO public USING ((is_platform_admin(auth.uid()) OR ((auth.uid() IS NOT NULL) AND (user_id = auth.uid()))));--> statement-breakpoint
CREATE POLICY "Users can update their own notifications" ON "notifications" AS PERMISSIVE FOR UPDATE TO public;--> statement-breakpoint
CREATE POLICY "Users can delete their own notifications" ON "notifications" AS PERMISSIVE FOR DELETE TO public;--> statement-breakpoint
CREATE POLICY "Users can view org tasks" ON "tasks" AS PERMISSIVE FOR SELECT TO public USING ((is_platform_admin(auth.uid()) OR (EXISTS ( SELECT 1
   FROM initiatives i
  WHERE ((i.id = tasks.initiative_id) AND (i.organization_id = get_user_org_id(auth.uid())))))));--> statement-breakpoint
CREATE POLICY "Admins managers and initiative owners can create tasks" ON "tasks" AS PERMISSIVE FOR INSERT TO public;--> statement-breakpoint
CREATE POLICY "Authorized users can update tasks" ON "tasks" AS PERMISSIVE FOR UPDATE TO public;--> statement-breakpoint
CREATE POLICY "Admins managers and initiative owners can delete tasks" ON "tasks" AS PERMISSIVE FOR DELETE TO public;--> statement-breakpoint
CREATE POLICY "Users can view org file attachments" ON "file_attachments" AS PERMISSIVE FOR SELECT TO public USING ((is_platform_admin(auth.uid()) OR (organization_id = get_user_org_id(auth.uid()))));--> statement-breakpoint
CREATE POLICY "Org users can create file attachments" ON "file_attachments" AS PERMISSIVE FOR INSERT TO public;--> statement-breakpoint
CREATE POLICY "Authorized users can delete file attachments" ON "file_attachments" AS PERMISSIVE FOR DELETE TO public;--> statement-breakpoint
CREATE POLICY "Users can view org automations" ON "automations" AS PERMISSIVE FOR SELECT TO public USING ((is_platform_admin(auth.uid()) OR (organization_id = get_user_org_id(auth.uid()))));--> statement-breakpoint
CREATE POLICY "Admins and managers can create automations" ON "automations" AS PERMISSIVE FOR INSERT TO public;--> statement-breakpoint
CREATE POLICY "Admins and managers can update automations" ON "automations" AS PERMISSIVE FOR UPDATE TO public;--> statement-breakpoint
CREATE POLICY "Admins and managers can delete automations" ON "automations" AS PERMISSIVE FOR DELETE TO public;--> statement-breakpoint
CREATE POLICY "Platform admins can remove platform_admins" ON "platform_admins" AS PERMISSIVE FOR DELETE TO public USING (is_platform_admin(auth.uid()));--> statement-breakpoint
CREATE POLICY "Platform admins can view platform_admins" ON "platform_admins" AS PERMISSIVE FOR SELECT TO public;--> statement-breakpoint
CREATE POLICY "Platform admins can add platform_admins" ON "platform_admins" AS PERMISSIVE FOR INSERT TO public;--> statement-breakpoint
CREATE POLICY "Users can view their own organization" ON "organizations" AS PERMISSIVE FOR SELECT TO public USING ((is_platform_admin(auth.uid()) OR (id = get_user_org_id(auth.uid()))));--> statement-breakpoint
CREATE POLICY "Admins can update their organization" ON "organizations" AS PERMISSIVE FOR UPDATE TO public;--> statement-breakpoint
CREATE POLICY "Platform admins can delete organizations" ON "organizations" AS PERMISSIVE FOR DELETE TO public;--> statement-breakpoint
CREATE POLICY "Users can view their organization domains" ON "organization_domains" AS PERMISSIVE FOR SELECT TO public USING ((is_platform_admin(auth.uid()) OR (organization_id = get_user_org_id(auth.uid()))));--> statement-breakpoint
CREATE POLICY "Admins can insert domains for their organization" ON "organization_domains" AS PERMISSIVE FOR INSERT TO public;--> statement-breakpoint
CREATE POLICY "Admins can update domains for their organization" ON "organization_domains" AS PERMISSIVE FOR UPDATE TO public;--> statement-breakpoint
CREATE POLICY "Admins can delete domains for their organization" ON "organization_domains" AS PERMISSIVE FOR DELETE TO public;--> statement-breakpoint
CREATE POLICY "Platform admins can delete users" ON "users_profile" AS PERMISSIVE FOR DELETE TO public USING (is_platform_admin(auth.uid()));--> statement-breakpoint
CREATE POLICY "Users can view their own profile" ON "users_profile" AS PERMISSIVE FOR SELECT TO public;--> statement-breakpoint
CREATE POLICY "Admins and managers can view org users" ON "users_profile" AS PERMISSIVE FOR SELECT TO public;--> statement-breakpoint
CREATE POLICY "Users can update their own profile" ON "users_profile" AS PERMISSIVE FOR UPDATE TO public;--> statement-breakpoint
CREATE POLICY "Admins can update org users" ON "users_profile" AS PERMISSIVE FOR UPDATE TO public;--> statement-breakpoint
CREATE POLICY "Authenticated users can view generic_domains" ON "generic_domains" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "Platform admins can manage generic_domains" ON "generic_domains" AS PERMISSIVE FOR ALL TO public;--> statement-breakpoint
CREATE POLICY "No direct select access to user_invitations" ON "user_invitations" AS PERMISSIVE FOR SELECT TO public USING (false);--> statement-breakpoint
CREATE POLICY "Admins and managers can create invitations" ON "user_invitations" AS PERMISSIVE FOR INSERT TO public;--> statement-breakpoint
CREATE POLICY "Admins and managers can update invitations" ON "user_invitations" AS PERMISSIVE FOR UPDATE TO public;--> statement-breakpoint
CREATE POLICY "Platform admins can delete invitations" ON "user_invitations" AS PERMISSIVE FOR DELETE TO public;--> statement-breakpoint
CREATE POLICY "Users can view org task dependencies" ON "task_dependencies" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((is_platform_admin(auth.uid()) OR (EXISTS ( SELECT 1
   FROM (tasks t
     JOIN initiatives i ON ((i.id = t.initiative_id)))
  WHERE ((t.id = task_dependencies.task_id) AND (i.organization_id = get_user_org_id(auth.uid())))))));--> statement-breakpoint
CREATE POLICY "Authorized users can create task dependencies" ON "task_dependencies" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "Authorized users can delete task dependencies" ON "task_dependencies" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "Users can view their own roles" ON "user_roles" AS PERMISSIVE FOR SELECT TO public USING ((is_platform_admin(auth.uid()) OR (user_id = auth.uid())));--> statement-breakpoint
CREATE POLICY "Admins and managers can view org user roles" ON "user_roles" AS PERMISSIVE FOR SELECT TO public;--> statement-breakpoint
CREATE POLICY "Admins can manage org user roles" ON "user_roles" AS PERMISSIVE FOR ALL TO public;--> statement-breakpoint
CREATE POLICY "Initiative managers can manage share links" ON "initiative_share_links" AS PERMISSIVE FOR ALL TO "authenticated" USING (can_manage_initiative(auth.uid(), initiative_id)) WITH CHECK (can_manage_initiative(auth.uid(), initiative_id));--> statement-breakpoint
CREATE POLICY "Platform admins can manage share links" ON "initiative_share_links" AS PERMISSIVE FOR ALL TO "authenticated";--> statement-breakpoint
CREATE POLICY "Users can view teams in their organization" ON "teams" AS PERMISSIVE FOR SELECT TO public USING ((is_platform_admin(auth.uid()) OR (organization_id = get_user_org_id(auth.uid()))));--> statement-breakpoint
CREATE POLICY "Admins and managers can create teams" ON "teams" AS PERMISSIVE FOR INSERT TO public;--> statement-breakpoint
CREATE POLICY "Admins and managers can update teams" ON "teams" AS PERMISSIVE FOR UPDATE TO public;--> statement-breakpoint
CREATE POLICY "Admins and managers can delete teams" ON "teams" AS PERMISSIVE FOR DELETE TO public;--> statement-breakpoint
CREATE POLICY "Users can view team members in their organization" ON "team_members" AS PERMISSIVE FOR SELECT TO public USING ((is_platform_admin(auth.uid()) OR (EXISTS ( SELECT 1
   FROM teams t
  WHERE ((t.id = team_members.team_id) AND (t.organization_id = get_user_org_id(auth.uid())))))));--> statement-breakpoint
CREATE POLICY "Admins and managers can add team members" ON "team_members" AS PERMISSIVE FOR INSERT TO public;--> statement-breakpoint
CREATE POLICY "Admins and managers can remove team members" ON "team_members" AS PERMISSIVE FOR DELETE TO public;--> statement-breakpoint
CREATE POLICY "Users can view org objectives" ON "objectives" AS PERMISSIVE FOR SELECT TO public USING ((is_platform_admin(auth.uid()) OR (organization_id = get_user_org_id(auth.uid()))));--> statement-breakpoint
CREATE POLICY "Admins and managers can create objectives" ON "objectives" AS PERMISSIVE FOR INSERT TO public;--> statement-breakpoint
CREATE POLICY "Admins and managers can update objectives" ON "objectives" AS PERMISSIVE FOR UPDATE TO public;--> statement-breakpoint
CREATE POLICY "Admins and managers can delete objectives" ON "objectives" AS PERMISSIVE FOR DELETE TO public;--> statement-breakpoint
CREATE POLICY "Admins managers can update any KRs" ON "key_results" AS PERMISSIVE FOR UPDATE TO public USING ((is_platform_admin(auth.uid()) OR ((organization_id = get_user_org_id(auth.uid())) AND (has_role(auth.uid(), 'admin'::app_role) OR has_role(auth.uid(), 'manager'::app_role))))) WITH CHECK ((is_platform_admin(auth.uid()) OR ((organization_id = get_user_org_id(auth.uid())) AND (has_role(auth.uid(), 'admin'::app_role) OR has_role(auth.uid(), 'manager'::app_role)))));--> statement-breakpoint
CREATE POLICY "Contributors can update owned KRs" ON "key_results" AS PERMISSIVE FOR UPDATE TO public;--> statement-breakpoint
CREATE POLICY "Users can view org key results" ON "key_results" AS PERMISSIVE FOR SELECT TO public;--> statement-breakpoint
CREATE POLICY "Admins and managers can create key results" ON "key_results" AS PERMISSIVE FOR INSERT TO public;--> statement-breakpoint
CREATE POLICY "Admins and managers can delete key results" ON "key_results" AS PERMISSIVE FOR DELETE TO public;--> statement-breakpoint
CREATE POLICY "Users can view org custom field definitions" ON "custom_field_definitions" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((is_platform_admin(auth.uid()) OR (organization_id = get_user_org_id(auth.uid()))));--> statement-breakpoint
CREATE POLICY "Admins and managers can manage custom field definitions" ON "custom_field_definitions" AS PERMISSIVE FOR ALL TO "authenticated";--> statement-breakpoint
CREATE POLICY "Users can view org custom field values" ON "custom_field_values" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((is_platform_admin(auth.uid()) OR (EXISTS ( SELECT 1
   FROM custom_field_definitions cfd
  WHERE ((cfd.id = custom_field_values.field_definition_id) AND (cfd.organization_id = get_user_org_id(auth.uid())))))));--> statement-breakpoint
CREATE POLICY "Authorized users can manage custom field values" ON "custom_field_values" AS PERMISSIVE FOR ALL TO "authenticated";--> statement-breakpoint
CREATE POLICY "Users can view org task watchers" ON "task_watchers" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((is_platform_admin(auth.uid()) OR (EXISTS ( SELECT 1
   FROM (tasks t
     JOIN initiatives i ON ((i.id = t.initiative_id)))
  WHERE ((t.id = task_watchers.task_id) AND (i.organization_id = get_user_org_id(auth.uid())))))));--> statement-breakpoint
CREATE POLICY "Org users can watch tasks" ON "task_watchers" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "Users can unwatch tasks" ON "task_watchers" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "Managers can manage watchers" ON "task_watchers" AS PERMISSIVE FOR ALL TO "authenticated";--> statement-breakpoint
CREATE POLICY "Share link managers can manage viewers" ON "initiative_share_viewers" AS PERMISSIVE FOR ALL TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM initiative_share_links sl
  WHERE ((sl.id = initiative_share_viewers.share_link_id) AND can_manage_initiative(auth.uid(), sl.initiative_id))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM initiative_share_links sl
  WHERE ((sl.id = initiative_share_viewers.share_link_id) AND can_manage_initiative(auth.uid(), sl.initiative_id)))));--> statement-breakpoint
CREATE POLICY "Platform admins can manage viewers" ON "initiative_share_viewers" AS PERMISSIVE FOR ALL TO "authenticated";
*/
